name: Story
description: Implementable story linked to an Epic
title: "[Story] <short title>"
labels:
  - "type: story"
body:
  - type: input
    id: epic
    attributes:
      label: Epic (optional)
      description: "Ссылка на родительский Epic (URL или #номер). Альтернативно: добавьте Story в Tasklist эпика."
      placeholder: "#<epic_issue_number> или https://github.com/<owner>/<repo>/issues/<epic_number>"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Краткая формулировка задачи"
      placeholder: "Добавить вычисление лотов на основе стопа и equity"
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: "- Лоты нормируются по min_lot/lot_step\n- Юнит-тесты покрывают 3 кейса\n- Документация обновлена"
  - type: textarea
    id: tasks
    attributes:
      label: Technical Tasks
      description: "Разбейте Story на конкретные задачи"
      placeholder: "- Реализовать compute_position_size\n- Получить pip_value_per_lot из MetaTraderClient.get_symbol_info\n- Написать тесты"