from dataclasses import dataclass, field
from datetime import datetime, time
from enum import Enum


class SignalType(Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NONE = "NONE"


class RangePeriod(Enum):
    MIN_5 = 5
    MIN_15 = 15
    MIN_30 = 30
    MIN_60 = 60


class Timeframe(Enum):
    M1 = 1
    M5 = 5
    M15 = 15
    M30 = 30
    H1 = 60
    H4 = 240
    D1 = 1440


@dataclass(frozen=True, slots=True)
class Candle:
    """OHLCV candle data."""

    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0

    def __post_init__(self):
        if self.high < self.low:
            raise ValueError("High must be >= Low")
        if self.high < max(self.open, self.close):
            raise ValueError("High must be >= Open and Close")
        if self.low > min(self.open, self.close):
            raise ValueError("Low must be <= Open and Close")


@dataclass(frozen=True, slots=True)
class OpeningRange:
    """The opening range high/low for a session."""

    high: float
    low: float
    start_time: datetime
    end_time: datetime

    @property
    def range_size(self) -> float:
        """Size of the opening range."""
        return self.high - self.low

    @property
    def midpoint(self) -> float:
        """Midpoint of the opening range."""
        return (self.high + self.low) / 2

    def is_above_range(self, price: float) -> bool:
        """Check if price is above the range."""
        return price > self.high

    def is_below_range(self, price: float) -> bool:
        """Check if price is below the range."""
        return price < self.low


@dataclass(frozen=True, slots=True)
class TradingSession:
    """Trading session time window."""

    start: time
    end: time
    name: str = "Default"

    def __post_init__(self):
        if self.start >= self.end:
            raise ValueError("Session start must be before end")

    def is_within_session(self, dt: datetime) -> bool:
        """Check if datetime is within trading session."""
        t = dt.time()
        return self.start <= t <= self.end

    def is_within_opening_range_period(self, dt: datetime, range_period: RangePeriod) -> bool:
        """Check if datetime is within the opening range period."""
        t = dt.time()
        range_end_minutes = self.start.hour * 60 + self.start.minute + range_period.value
        range_end = time(hour=range_end_minutes // 60, minute=range_end_minutes % 60)
        return self.start <= t < range_end


@dataclass(frozen=True, slots=True)
class ConfirmationInfo:
    """Information about the breakout confirmation."""

    timeframe: Timeframe
    candle: Candle
    breakout_distance: float  # How far price closed beyond the range
    breakout_pct: float  # Percentage beyond range

    @property
    def body_size(self) -> float:
        """Size of the confirmation candle body."""
        return abs(self.candle.close - self.candle.open)

    @property
    def is_bullish(self) -> bool:
        """Whether the confirmation candle is bullish."""
        return self.candle.close > self.candle.open

    @property
    def is_bearish(self) -> bool:
        """Whether the confirmation candle is bearish."""
        return self.candle.close < self.candle.open


@dataclass(slots=True)
class Signal:
    """Trading signal generated by the strategy."""

    signal_type: SignalType
    lots: float
    timestamp: datetime
    entry_price: float
    opening_range: OpeningRange
    confirmation_candle: Candle | None = None
    confirmation_info: ConfirmationInfo | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    metadata: dict = field(default_factory=dict)

    @property
    def risk_reward_ratio(self) -> float | None:
        """Calculate risk/reward ratio if SL and TP are set."""
        if self.stop_loss is None or self.take_profit is None:
            return None
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        return reward / risk if risk > 0 else None

    @property
    def confirmation_timeframe(self) -> Timeframe | None:
        """Get the timeframe used for confirmation."""
        if self.confirmation_info is not None:
            return self.confirmation_info.timeframe
        return None


# Common trading sessions
ORB_SESSION = TradingSession(start=time(9, 30), end=time(10, 30), name="ORB Regular Hours")
NYSE_SESSION = TradingSession(start=time(9, 30), end=time(16, 0), name="NYSE Regular Hours")
NASDAQ_SESSION = TradingSession(start=time(9, 30), end=time(16, 0), name="NASDAQ Regular Hours")

FOREX_LONDON = TradingSession(start=time(8, 0), end=time(16, 0), name="London Session")
FOREX_NY = TradingSession(start=time(13, 0), end=time(21, 0), name="New York Session")
